# Documentation: https://roots.io/trellis/docs/remote-server-setup/
wordpress_sites:
  svt-wp-cms:
    site_hosts:
      - wp-test01.testsavoteur.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:dailysecret/svt-wp-cms.git # replace with your Git repo URL
    branch: master
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
      # cert: ~/ssl/example.com.crt
      # key: ~/ssl/example.com.key
    cache:
      enabled: false
      duration: 30s
    env:
      disable_wp_cron: true
      wp_home: http://wp-test01.testsavoteur.com
      wp_siteurl: http://wp-test01.testsavoteur.com/wp
      wp_env: staging
      db_name: wp_cms_staging
      db_user: wp_cms_dbuser
      # Define the following variables in group_vars/staging/vault.yml
      # db_password:
      # auth_key:
      # secure_auth_key:
      # logged_in_key:
      # nonce_key:
      # auth_salt:
      # secure_auth_salt:
      # logged_in_salt:
      # nonce_salt:
